### ISSUE TITLE
Looking forward to your open source code

### ISSUE THREAD

**Issue by Nioolek** [hao1635/ASCON#1]
Your paper is quite novel and I really appreciate your talent. I would like to know when you plan to make your code public?

**Comment by hao1635** [comment]
> Your paper is quite novel and I really appreciate your talent. I would like to know when you plan to make your code public?

Thanks! Already uploaded.

**Comment by hhhljf** [comment]
Thanks for Ur novel work. I am trying to train the model on Moya dataset. I followed the command of traing prived by you. When the  runing the python file of models.networks,  I met a error warning as follows:
Traceback (most recent call last):
  File "/dg_hpc/CNG/lijf/ASCON-main/train.py", line 72, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 128, in optimize_parameters
    self.loss_D = self.compute_D_loss()
  File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 160, in compute_D_loss
    self.loss_D = self.MAC_Net(self.real_B, self.fake_B.detach())
  File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 189, in MAC_Net
    feat_k_pool_1, sample_ids, sample_local_ids, sample_top_idxs = self.netProjection_target(patch_size,feat_k_1, self.num_patches,None,None,None,pixweght=None)
  File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dg_hpc/CNG/lijf/ASCON-main/models/networks.py", line 130, in forward
    N_patches=num_patches[feat_id]
IndexError: list index out of range
I have checked the value of num_patches. num_patches seems should be a array.  However, I find num_patches is a predefined int value of 256. I wonder how to eliminate the error. Thanks!

**Comment by fightinggirl0** [comment]
> Thanks for Ur novel work. I am trying to train the model on Moya dataset. I followed the command of traing prived by you. When the runing the python file of models.networks, I met a error warning as follows: Traceback (most recent call last): File "/dg_hpc/CNG/lijf/ASCON-main/train.py", line 72, in model.optimize_parameters() # calculate loss functions, get gradients, update network weights File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 128, in optimize_parameters self.loss_D = self.compute_D_loss() File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 160, in compute_D_loss self.loss_D = self.MAC_Net(self.real_B, self.fake_B.detach()) File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 189, in MAC_Net feat_k_pool_1, sample_ids, sample_local_ids, sample_top_idxs = self.netProjection_target(patch_size,feat_k_1, self.num_patches,None,None,None,pixweght=None) File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward return self.module(*inputs[0], **kwargs[0]) File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/dg_hpc/CNG/lijf/ASCON-main/models/networks.py", line 130, in forward N_patches=num_patches[feat_id] IndexError: list index out of range I have checked the value of num_patches. num_patches seems should be a array. However, I find num_patches is a predefined int value of 256. I wonder how to eliminate the error. Thanks!

Hello, have you solved this problem now? I have also encountered the same problem, looking forward to your reply, thank you

**Comment by hhhljf** [comment]
The auther has been update the tranining command. just follow the new command will be ok.




·&nbsp;摩兲輪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hao1635/ASCON"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午2:09
***@***.***&gt;;
抄送:&nbsp;"· ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hao1635/ASCON] Looking forward to your open source code (Issue #1)





  
Thanks for Ur novel work. I am trying to train the model on Moya dataset. I followed the command of traing prived by you. When the runing the python file of models.networks, I met a error warning as follows: Traceback (most recent call last): File "/dg_hpc/CNG/lijf/ASCON-main/train.py", line 72, in model.optimize_parameters() # calculate loss functions, get gradients, update network weights File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 128, in optimize_parameters self.loss_D = self.compute_D_loss() File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 160, in compute_D_loss self.loss_D = self.MAC_Net(self.real_B, self.fake_B.detach()) File "/dg_hpc/CNG/lijf/ASCON-main/models/ASCON_model.py", line 189, in MAC_Net feat_k_pool_1, sample_ids, sample_local_ids, sample_top_idxs = self.netProjection_target(patch_size,feat_k_1, self.num_patches,None,None,None,pixweght=None) File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward return self.module(*inputs[0], **kwargs[0]) File "/dg_workfs/CNG/lijf/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/dg_hpc/CNG/lijf/ASCON-main/models/networks.py", line 130, in forward N_patches=num_patches[feat_id] IndexError: list index out of range I have checked the value of num_patches. num_patches seems should be a array. However, I find num_patches is a predefined int value of 256. I wonder how to eliminate the error. Thanks!
  
Hello, have you solved this problem now? I have also encountered the same problem, looking forward to your reply, thank you

**Comment by Nioolek** [comment]
I thought it would be better for the user experience to upload the code to convert the mayo dataset to npy files

**Comment by hao1635** [comment]
> I thought it would be better for the user experience to upload the code to convert the mayo dataset to npy files

Updated.
